package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallCard;
import org.linlinjava.litemall.db.domain.LitemallCardExample;

public interface LitemallCardMapper {

    int batchSaveCard(List<LitemallCard> list);
   int batchUpdateCard(List<LitemallCard> list);
    long countByExample(LitemallCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    int insert(LitemallCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    int insertSelective(LitemallCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    LitemallCard selectOneByExample(LitemallCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    LitemallCard selectOneByExampleSelective(@Param("example") LitemallCardExample example, @Param("selective") LitemallCard.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    List<LitemallCard> selectByExampleSelective(@Param("example") LitemallCardExample example, @Param("selective") LitemallCard.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    List<LitemallCard> selectByExample(LitemallCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    LitemallCard selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") LitemallCard.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    LitemallCard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallCard record, @Param("example") LitemallCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallCard record, @Param("example") LitemallCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallCard record);
}